#include <stdio.h>
#include <stdlib.h>
#include "lyrid/ast.h"
#include "parser.tab.h"   /* Generated by Bison */
#include "lex.yy.h"       /* Generated by Flex */

extern int yyparse(lyrid_program **prog);
extern FILE *yyin;

lyrid_program *
lyrid_parse_file(const char *filename)
{
    FILE *file = fopen(filename, "r");
    if (file == NULL)
    {
        lyrid_program *prog = malloc(sizeof(lyrid_program));
        prog->is_valid = false;
        prog->error_message = strdup("Failed to open input file");
        prog->statements = NULL;
        prog->count = 0;
        return prog;
    }

    yyin = file;
    lyrid_program *prog = NULL;
    yyparse(&prog);
    fclose(file);
    return prog;
}

lyrid_program *
lyrid_parse_string(const char *source)
{
    YY_BUFFER_STATE buf = yy_scan_string(source);
    lyrid_program *prog = NULL;
    yyparse(&prog);
    yy_delete_buffer(buf);
    return prog;
}
